/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConnectionLayoutRouteImport } from './routes/_ConnectionLayout'
import { Route as ConnectionLayoutIndexRouteImport } from './routes/_ConnectionLayout/index'
import { Route as ConnectionLayoutConnectionIdRouteImport } from './routes/_ConnectionLayout/$connectionId'
import { Route as ConnectionLayoutExploreConnectionIdRouteImport } from './routes/_ConnectionLayout/explore.$connectionId'

const ConnectionLayoutRoute = ConnectionLayoutRouteImport.update({
  id: '/_ConnectionLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionLayoutIndexRoute = ConnectionLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConnectionLayoutRoute,
} as any)
const ConnectionLayoutConnectionIdRoute =
  ConnectionLayoutConnectionIdRouteImport.update({
    id: '/$connectionId',
    path: '/$connectionId',
    getParentRoute: () => ConnectionLayoutRoute,
  } as any)
const ConnectionLayoutExploreConnectionIdRoute =
  ConnectionLayoutExploreConnectionIdRouteImport.update({
    id: '/explore/$connectionId',
    path: '/explore/$connectionId',
    getParentRoute: () => ConnectionLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ConnectionLayoutIndexRoute
  '/$connectionId': typeof ConnectionLayoutConnectionIdRoute
  '/explore/$connectionId': typeof ConnectionLayoutExploreConnectionIdRoute
}
export interface FileRoutesByTo {
  '/$connectionId': typeof ConnectionLayoutConnectionIdRoute
  '/': typeof ConnectionLayoutIndexRoute
  '/explore/$connectionId': typeof ConnectionLayoutExploreConnectionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_ConnectionLayout': typeof ConnectionLayoutRouteWithChildren
  '/_ConnectionLayout/$connectionId': typeof ConnectionLayoutConnectionIdRoute
  '/_ConnectionLayout/': typeof ConnectionLayoutIndexRoute
  '/_ConnectionLayout/explore/$connectionId': typeof ConnectionLayoutExploreConnectionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$connectionId' | '/explore/$connectionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/$connectionId' | '/' | '/explore/$connectionId'
  id:
    | '__root__'
    | '/_ConnectionLayout'
    | '/_ConnectionLayout/$connectionId'
    | '/_ConnectionLayout/'
    | '/_ConnectionLayout/explore/$connectionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ConnectionLayoutRoute: typeof ConnectionLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_ConnectionLayout': {
      id: '/_ConnectionLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ConnectionLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_ConnectionLayout/': {
      id: '/_ConnectionLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ConnectionLayoutIndexRouteImport
      parentRoute: typeof ConnectionLayoutRoute
    }
    '/_ConnectionLayout/$connectionId': {
      id: '/_ConnectionLayout/$connectionId'
      path: '/$connectionId'
      fullPath: '/$connectionId'
      preLoaderRoute: typeof ConnectionLayoutConnectionIdRouteImport
      parentRoute: typeof ConnectionLayoutRoute
    }
    '/_ConnectionLayout/explore/$connectionId': {
      id: '/_ConnectionLayout/explore/$connectionId'
      path: '/explore/$connectionId'
      fullPath: '/explore/$connectionId'
      preLoaderRoute: typeof ConnectionLayoutExploreConnectionIdRouteImport
      parentRoute: typeof ConnectionLayoutRoute
    }
  }
}

interface ConnectionLayoutRouteChildren {
  ConnectionLayoutConnectionIdRoute: typeof ConnectionLayoutConnectionIdRoute
  ConnectionLayoutIndexRoute: typeof ConnectionLayoutIndexRoute
  ConnectionLayoutExploreConnectionIdRoute: typeof ConnectionLayoutExploreConnectionIdRoute
}

const ConnectionLayoutRouteChildren: ConnectionLayoutRouteChildren = {
  ConnectionLayoutConnectionIdRoute: ConnectionLayoutConnectionIdRoute,
  ConnectionLayoutIndexRoute: ConnectionLayoutIndexRoute,
  ConnectionLayoutExploreConnectionIdRoute:
    ConnectionLayoutExploreConnectionIdRoute,
}

const ConnectionLayoutRouteWithChildren =
  ConnectionLayoutRoute._addFileChildren(ConnectionLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ConnectionLayoutRoute: ConnectionLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
