/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExplorerLayoutRouteImport } from './routes/_ExplorerLayout'
import { Route as ConnectionLayoutRouteImport } from './routes/_ConnectionLayout'
import { Route as ConnectionLayoutIndexRouteImport } from './routes/_ConnectionLayout/index'
import { Route as ConnectionLayoutConnectionIdRouteImport } from './routes/_ConnectionLayout/$connectionId'
import { Route as ExplorerLayoutExploreConnectionIdRouteImport } from './routes/_ExplorerLayout/explore.$connectionId'

const ExplorerLayoutRoute = ExplorerLayoutRouteImport.update({
  id: '/_ExplorerLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionLayoutRoute = ConnectionLayoutRouteImport.update({
  id: '/_ConnectionLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionLayoutIndexRoute = ConnectionLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConnectionLayoutRoute,
} as any)
const ConnectionLayoutConnectionIdRoute =
  ConnectionLayoutConnectionIdRouteImport.update({
    id: '/$connectionId',
    path: '/$connectionId',
    getParentRoute: () => ConnectionLayoutRoute,
  } as any)
const ExplorerLayoutExploreConnectionIdRoute =
  ExplorerLayoutExploreConnectionIdRouteImport.update({
    id: '/explore/$connectionId',
    path: '/explore/$connectionId',
    getParentRoute: () => ExplorerLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ConnectionLayoutIndexRoute
  '/$connectionId': typeof ConnectionLayoutConnectionIdRoute
  '/explore/$connectionId': typeof ExplorerLayoutExploreConnectionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof ConnectionLayoutIndexRoute
  '/$connectionId': typeof ConnectionLayoutConnectionIdRoute
  '/explore/$connectionId': typeof ExplorerLayoutExploreConnectionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_ConnectionLayout': typeof ConnectionLayoutRouteWithChildren
  '/_ExplorerLayout': typeof ExplorerLayoutRouteWithChildren
  '/_ConnectionLayout/$connectionId': typeof ConnectionLayoutConnectionIdRoute
  '/_ConnectionLayout/': typeof ConnectionLayoutIndexRoute
  '/_ExplorerLayout/explore/$connectionId': typeof ExplorerLayoutExploreConnectionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$connectionId' | '/explore/$connectionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$connectionId' | '/explore/$connectionId'
  id:
    | '__root__'
    | '/_ConnectionLayout'
    | '/_ExplorerLayout'
    | '/_ConnectionLayout/$connectionId'
    | '/_ConnectionLayout/'
    | '/_ExplorerLayout/explore/$connectionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ConnectionLayoutRoute: typeof ConnectionLayoutRouteWithChildren
  ExplorerLayoutRoute: typeof ExplorerLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_ExplorerLayout': {
      id: '/_ExplorerLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ExplorerLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_ConnectionLayout': {
      id: '/_ConnectionLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ConnectionLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_ConnectionLayout/': {
      id: '/_ConnectionLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ConnectionLayoutIndexRouteImport
      parentRoute: typeof ConnectionLayoutRoute
    }
    '/_ConnectionLayout/$connectionId': {
      id: '/_ConnectionLayout/$connectionId'
      path: '/$connectionId'
      fullPath: '/$connectionId'
      preLoaderRoute: typeof ConnectionLayoutConnectionIdRouteImport
      parentRoute: typeof ConnectionLayoutRoute
    }
    '/_ExplorerLayout/explore/$connectionId': {
      id: '/_ExplorerLayout/explore/$connectionId'
      path: '/explore/$connectionId'
      fullPath: '/explore/$connectionId'
      preLoaderRoute: typeof ExplorerLayoutExploreConnectionIdRouteImport
      parentRoute: typeof ExplorerLayoutRoute
    }
  }
}

interface ConnectionLayoutRouteChildren {
  ConnectionLayoutConnectionIdRoute: typeof ConnectionLayoutConnectionIdRoute
  ConnectionLayoutIndexRoute: typeof ConnectionLayoutIndexRoute
}

const ConnectionLayoutRouteChildren: ConnectionLayoutRouteChildren = {
  ConnectionLayoutConnectionIdRoute: ConnectionLayoutConnectionIdRoute,
  ConnectionLayoutIndexRoute: ConnectionLayoutIndexRoute,
}

const ConnectionLayoutRouteWithChildren =
  ConnectionLayoutRoute._addFileChildren(ConnectionLayoutRouteChildren)

interface ExplorerLayoutRouteChildren {
  ExplorerLayoutExploreConnectionIdRoute: typeof ExplorerLayoutExploreConnectionIdRoute
}

const ExplorerLayoutRouteChildren: ExplorerLayoutRouteChildren = {
  ExplorerLayoutExploreConnectionIdRoute:
    ExplorerLayoutExploreConnectionIdRoute,
}

const ExplorerLayoutRouteWithChildren = ExplorerLayoutRoute._addFileChildren(
  ExplorerLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ConnectionLayoutRoute: ConnectionLayoutRouteWithChildren,
  ExplorerLayoutRoute: ExplorerLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
